import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { GraduationCap, LayoutDashboard, Users, LogOut, ArrowUpRight, ShieldCheck, Command } from 'lucide-react';
import { useAuth } from '../auth/context';
import { initials } from '../utils/format';
import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
export function Shell(){const {user,logout}=useAuth();const navigate=useNavigate();const location=useLocation();
  useEffect(()=>{document.querySelector<HTMLElement>('main h1')?.focus();},[location.pathname]);
  return <div className="app-shell"><a className="skip" href="#main">Skip to content</a><aside className="sidebar"><a href="/students" className="brand"><span className="brand-icon"><GraduationCap size={24}/></span>readiness<span className="brand-period">.</span></a><div className="workspace-label">WORKSPACE</div><div className="organization"><div className="org-icon">{user?.tenantName.slice(0,1)}</div><div><strong>{user?.tenantName}</strong><small>Training organization</small></div></div><nav aria-label="Main navigation"><span className="nav-heading">CONTROL CENTER</span><NavLink to="/students"><LayoutDashboard size={18}/> Student overview <span className="nav-count"><Users size={14}/></span></NavLink></nav><div className="sidebar-bottom"><div className="workspace-note"><ShieldCheck size={21}/><strong>Your workspace, protected.</strong><p>Assessment evidence stays within your organization.</p><span>Tenant-isolated access <ArrowUpRight size={13}/></span></div><div className="profile"><span className="avatar">{initials(user?.name??'User')}</span><div><strong>{user?.name.split(' · ')[0]}</strong><small>{user?.role.toLowerCase()}</small></div><button aria-label="Sign out or switch account" title="Sign out or switch account" onClick={()=>{void logout().finally(()=>navigate('/login'));}}><LogOut size={17}/></button></div></div></aside><div className="workspace"><header className="topbar"><span>Workspace <span className="crumb">/</span> <strong>Student readiness</strong></span><span className="private-label"><span className="green-dot"/>Private workspace <Command size={15}/></span></header><main id="main"><Outlet key={user?.sessionId}/></main><footer>READINESS CONTROL CENTER<span>Evidence-led learning. Confident next steps.</span></footer></div></div>;
}
